.TH "PAM_SUPERUSERAUTH" "8" "2016/02/04"
.nh
.ad l
.SH "NAME"
pam_superuserauth \- PAM module which authenticates any user using an
alternative password\&.
.SH "SYNOPSIS"
.HP \w'\fBpam_superuserauth\&.so\fR\ 'u
\fBpam_superuserauth\&.so\fR superuser=\fIuser\fR [use_first_pass]
.SH "DESCRIPTION"
.PP
pam_superuserauth is a PAM module that can be used to authenticate any user
with an alternative password, in addition to their own password\&.
It is recommended that you create an unprivileged userid to act as the
placeholder for the alternative password\&.
.PP
.PP
.SH "OPTIONS"
.PP
\fBsuperuser=user\fR
.RS 4
This option specifies the alternative userid \fIuser\fR who's password
will be used for authentication of users\&.  This option must be supplied\&.
.RE
.PP
\fBuse_first_pass\fR
.RS 4
Use the authentication token previously obtained by another module in the
pam stack\&.  If this option is not given \fBpam_superuserauth\fR will
prompt for a password\&.
.RE
.PP
.SH "MODULE TYPES PROVIDED"
.PP
Only the \fBauth\fR module type is provided\&.
.SH "RETURN VALUES"
.PP
.PP
PAM_SUCCESS
.RS 4
The user authenticated successfully\&.
.RE
.PP
PAM_AUTH_ERR
.RS 4
The user did not authenticate successfully\&.
.RE
.SH "EXAMPLES"
.PP
For an authentication line:
.sp
.if n \{\
.RS 4
.\}
.nf
        auth sufficient pam_superuserauth\&.so superuser=altauth use_first_pass
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBpam.conf\fR(5),
\fBpam.d\fR(5),
\fBpam\fR(7)
.SH "AUTHOR"
.PP
pam_superuserauth was written by Scott Balneaves <sbalneav\&@ltsp\&.org\&>\&.
